### ISSUE TITLE
Error running examples

### ISSUE THREAD

**Issue by ni-chen** [Biomedical-Imaging-Group/GlobalBioIm#2]
Hi,

I got an error when I run one of the examples of Deconv_Ls_NonNeg_NoReg.m, when Installing OptimPackLegacy, the below error came out:

> Building with 'Microsoft Visual C++ 2017 (C)'.
> Error using mex
> opl_vmlmb.c
> P:\work\research\toolbox\GlobalBioIm\Opti\OptiUtils\MatlabOptimPack\OptimPackLegacy-master\src\opl_vmlmb.c(100):
> error C2059: syntax error: '<parameter-list>'
> P:\work\research\toolbox\GlobalBioIm\Opti\OptiUtils\MatlabOptimPack\OptimPackLegacy-master\src\opl_vmlmb.c(104):
> error C2059: syntax error: '<parameter-list>'
> 
> Error in installOptimPack (line 37)
> eval(['mex ',matDir,'m_opl_vmlmb_get_reason.c ', CFiles,MexOpt]);
> Error in OptiVMLMB (line 97)
>                 installOptimPack();
> Error in Deconv_LS_NonNeg_NoReg (line 68)
> VMLMB=OptiVMLMB(F,0.,[]);   

I'm using Win10 and Matlab 2019 a with 'Microsoft Visual C++ 2017 (C)'. Hope this can be resolved soon.

Thanks.

**Comment by esoubies** [comment]
Hi,

Last week someone had the same problem and the solution was just to change the C++ compiler to the C compiler in Matlab.
Best regards
Emmanuel Soubies

**Comment by ni-chen** [comment]
Hi Emmanuel,

It works.
Thanks a lot.

Ni
