### ISSUE TITLE
Acknowledging EPFL and CIBM

### ISSUE THREAD

**Issue by poldap** [Biomedical-Imaging-Group/GlobalBioIm#37]
After discussing with Michael it seems it would be convenient to acknowledge CIBM by adding a logo somewhere. I think the most natural would be to also add an EPFL one. If you agree I will go ahead and make a PR with respect to that. Thanks ;-)

**Comment by esoubies** [comment]
Hi Pol, seems to be a good idea, for me you can go ahead ! Thanks
